### ISSUE TITLE
aclpwn error 

### ISSUE THREAD

**Issue by 0xElmalky** [fox-it/aclpwn.py#11]
aclpwn -f svc-alfresco -t htb.local --domain htb.local --server 10.10.10.161 --database bolt://LOCALHOST:7687 --database-user neo4j --database-password ahmed
Please supply the password or LM:NTLM hashes of the account you are escalating from: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/neobolt/addressing.py", line 132, in dns_resolve
    info = getaddrinfo(address[0], address[1], 0, SOCK_STREAM, IPPROTO_TCP)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/aclpwn", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/ahmed/.local/lib/python3.11/site-packages/aclpwn/__init__.py", line 93, in main
    database.init_driver(args.database, args.database_user, args.database_password)
  File "/home/ahmed/.local/lib/python3.11/site-packages/aclpwn/database.py", line 14, in init_driver
    driver = GraphDatabase.driver(uri, auth=(user, password))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmed/.local/lib/python3.11/site-packages/neo4j/__init__.py", line 120, in driver
    return Driver(uri, **config)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmed/.local/lib/python3.11/site-packages/neo4j/__init__.py", line 161, in __new__
    return subclass(uri, **config)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmed/.local/lib/python3.11/site-packages/neo4j/__init__.py", line 235, in __new__
    pool.release(pool.acquire())
                 ^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 715, in acquire
    return self.acquire_direct(self.address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 608, in acquire_direct
    connection = self.connector(address, error_handler=self.connection_error_handler)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ahmed/.local/lib/python3.11/site-packages/neo4j/__init__.py", line 232, in connector
    return connect(address, **dict(config, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/neobolt/direct.py", line 958, in connect
    resolver.dns_resolve()
  File "/usr/lib/python3/dist-packages/neobolt/addressing.py", line 134, in dns_resolve
    raise AddressError("Cannot resolve address {!r}".format(address))
neobolt.addressing.AddressError: Cannot resolve address Address(host='bolt', port=7687)

can anyone help

**Comment by dirkjanm** [comment]
pretty sure the database parameter only accepts a hostname. You'll probably run into plenty of other errors though since this project has not been updated for a long time

**Comment by RajChowdhury240** [comment]
Does it work with BloodHound Community tool also ?
