### ISSUE TITLE
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 22 (offset: 21))

### ISSUE THREAD

**Issue by lanjianchun** [fox-it/aclpwn.py#4]
Traceback (most recent call last):
  File "/usr/local/bin/aclpwn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/aclpwn/__init__.py", line 108, in main
    fromres = session.run(q % args.from_type.capitalize(), name=from_object)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 217, in run
    self._autoResult._run(query, parameters, self._config.database, self._config.default_access_mode, self._bookmarks, **kwparameters)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_bolt4x0.py", line 353, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_bolt4x0.py", line 552, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.CypherSyntaxError: {code: Neo.ClientError.Statement.SyntaxError} {message: The old parameter syntax `{param}` is no longer supported. Please use `$param` instead (line 1, column 22 (offset: 21))
"MATCH (n:User {name: {name}}) RETURN n"

seems that neo4j need to update!  how to fix it!

**Comment by tiyeuse** [comment]
Hello, I'm facing the same issue with a fresh install of aclpwn.
It can be great to also modify the requirements.txt and change this:
```
neo4j-driver==1.7.0
neo4j==1.7.0
requests
```

**Comment by eriakort** [comment]
Hi, having similar issues right now. A fresh install of aclpwn. When I change the parameter as mentioned from {name} to $name it does skip this file without issues but shows something else from another file as follows:

Traceback (most recent call last):
  File "/usr/local/bin/aclpwn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/aclpwn/__init__.py", line 120, in main
    paths = pathfinding.dijkstra_find(fromid, toid, args.database)
  File "/usr/local/lib/python3.9/dist-packages/aclpwn/pathfinding.py", line 34, in dijkstra_find
    data = resp.json()
  File "/usr/local/lib/python3.9/dist-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


I honestly don't know how to fix this. Any solutions out there? Thanks in advance.
