### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by Bowsergit** [fox-it/aclpwn.py#7]
root@kali# pip install aclpwn

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                                                                                                                                                
Collecting aclpwn
  Using cached aclpwn-1.0.0-py2-none-any.whl (18 kB)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages (from aclpwn) (2.18.4)
Requirement already satisfied: ldap3>=2.5 in /usr/local/lib/python2.7/dist-packages (from aclpwn) (2.7)
Collecting neo4j-driver
  Using cached neo4j-driver-4.1.1.tar.gz (67 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-Lf6zcC/neo4j-driver/setup.py'"'"'; __file__='"'"'/tmp/pip-install-Lf6zcC/neo4j-driver/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8zIcNT                                                                                                                                     
         cwd: /tmp/pip-install-Lf6zcC/neo4j-driver/                                                                                                                                   
    Complete output (8 lines):                                                                                                                                                        
    Traceback (most recent call last):                                                                                                                                                
      File "<string>", line 1, in <module>                                                                                                                                            
      File "/tmp/pip-install-Lf6zcC/neo4j-driver/setup.py", line 25, in <module>                                                                                                      
        from neo4j.meta import package, version                                                                                                                                       
      File "neo4j/__init__.py", line 123                                                                                                                                              
        def driver(cls, uri, *, auth=None, **config):                                                                                                                                 
                              ^                                                                                                                                                       
    SyntaxError: invalid syntax                                                                                                                                                       
    ----------------------------------------                                                                                                                                          
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

any idea what the issue is and how to fix it so I can install aclpwn? I'm a newbie ..

**Comment by dirkjanm** [comment]
Seems likely that you'll need python 3.6+ to run it.

**Comment by dirkjanm** [comment]
You may also need to follow the instructions in #6
